INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("MHS Choir Fundraiser", "School Fundraiser", 5000, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help our debate club go to D.C.", "School Fundraiser", 1000, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Holy Hellraiser H.S. Band Needs Money", "School Fundraiser", 2500, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help me get a nose job", "Medical", 15000, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hawaii Here I Come!", "Vacation", 1200, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Send our little league team to W.S!", "Team Fundraiser", 500, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("I got web toes!", "Medical", 50000, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dream Vacation in Greece", "Vacation", 1000, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("H.S. Basketball Fundraiser", "Team Fundraiser", 2000, "Jan 1", "Jan 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Football team needs helmets", "Team Fundraiser", 1800, "Jan 1", "Jan 30");
INSERT INTO users (name, age) VALUES ("Adam", 20);
INSERT INTO users (name, age) VALUES ("Bob", 54);
INSERT INTO users (name, age) VALUES ("Charles", 45);
INSERT INTO users (name, age) VALUES ("Dylan", 18);
INSERT INTO users (name, age) VALUES ("Edgar", 34);
INSERT INTO users (name, age) VALUES ("Frank", 74);
INSERT INTO users (name, age) VALUES ("Gene", 67);
INSERT INTO users (name, age) VALUES ("Harry", 32);
INSERT INTO users (name, age) VALUES ("Ian", 19);
INSERT INTO users (name, age) VALUES ("Jorge", 40);
INSERT INTO users (name, age) VALUES ("Kathy", 30);
INSERT INTO users (name, age) VALUES ("Lucas", 98);
INSERT INTO users (name, age) VALUES ("Maddie", 90);
INSERT INTO users (name, age) VALUES ("Nancy", 36);
INSERT INTO users (name, age) VALUES ("Oprah", 59);
INSERT INTO users (name, age) VALUES ("Penelope", 31);
INSERT INTO users (name, age) VALUES ("Quincy", 24);
INSERT INTO users (name, age) VALUES ("Raina", 28);
INSERT INTO users (name, age) VALUES ("Sam", 23);
INSERT INTO users (name, age) VALUES ("Todd", 47);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 20,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 19,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (18, 18,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 17,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 16,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 15,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (454, 14,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (64, 13,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 12,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 11,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 10,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (743, 9,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (74, 8,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (32, 7,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (97, 6,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 5,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (101, 4,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (57, 3,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (743, 2,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (46, 1,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (78, 20,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (423, 1,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (743, 19,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34, 2,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (67, 18,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 3,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (458, 17,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (154, 4,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (16, 16,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (41, 5,10);
